version: "3"
services:
  backend:
    image: itfest-backend:latest
    restart: always
    ports:
      - "8080:3000"
    environment:
      DB_URL: "mysql://root:password@db/arkav"
      DB_NAME: arkav
      DB_TYPE: mysql

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: arkav

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  db-vol: {}
