name: Build and Push to Docker
on:
  push:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: arkavidia-hmif/itfest-backend/itfestbackend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run deployment script over SSH
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      with:
        args: "/root/deployment-scripts/itfest/deploy-staging-itfest.sh"
