name: Build and Push to Docker
on:
  push:
    branches:
      - master
  create:
    tags:
      - "**"
jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Staging to Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: arkavidia-hmif/itfest-backend/builds
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          tags: "latest,staging"

  build-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get tag name
        id: get_tag_name
        if: github.event_name == 'create'
        run: echo ::set-output name=TAG_NAME::"${GITHUB_REF/refs\/tags\//}"
      - name: Publish Production to Registry
        if: github.event_name == 'create'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: arkavidia-hmif/itfest-backend/builds
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          tags: "production,${{ steps.get_tag_name.outputs.TAG_NAME }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-staging, build-production]
    steps:
      - name: Run deployment script over SSH
        uses: maddox/actions/ssh@master
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        with:
          args: "cd /root/ && docker-compose pull && docker-compose up -d"
